name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dotnet

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Output Run Number
      run: echo "1.0.0.${{ github.run_number }}"
    - name: Build
      run: dotnet build /p:AssemblyVersion=1.0.0.${{ github.run_number }} /property:Version=1.0.0.${{ github.run_number }} --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Push Nuget
      run: dotnet nuget push dotnet\bin\Debug\TeamHitori.Mulplay.Shared.Storage.1.0.0.${{ github.run_number }}.nupkg --api-key {{ secrets.NUGETKEY }} --source https://api.nuget.org/v3/index.json

